spring:
  datasource:
    url: jdbc:mysql://dev-server:3300/app
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    password: Passw0rd
    cluster:
      nodes: dev-server:7001,dev-server:7002,dev-server:7003,dev-server:7004,dev-server:7005,dev-server:7006
  elasticsearch:
    rest:
      uris: [ http://dev-server:9201 ,http://dev-server:9202 ,http://dev-server:9203 ]
  rabbitmq:
    host: dev-server
    port: 5670
    username: rabbit
    password: Passw0rd
  jpa:
    properties:
      hibernate:
        #        show_sql: true
        #        use_sql_comments: true
        #        format_sql: true
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-request-size: 10GB
      max-file-size: 1GB
  #  main:
  #    lazy-initialization: true
  cache:
    redis:
      time-to-live: 600000 #10 minutes
  data:
    mongodb:
      host: dev-server
      port: 27000
      database: app
      username: apps
      password: apps
  devtools:
    restart:
      additional-paths:
        - ./application/boot/build/classes/java/main
        - ./application/database/build/classes/java/main
        - ./application/service/build/classes/java/main
        - ./application/utils/build/classes/java/main
        - ./library/extend/build/classes/java/main
        - ./library/lang/build/classes/java/main
server:
  port: 3333
