spring:
  datasource:
    url: jdbc:mysql://dev-server:3306/app
    username: apps
    password: apps
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: dev-server
  #    password: Passw0rd
  #    cluster:
  #      nodes: dev-server:7000,dev-server:7001,dev-server:7002,dev-server:7003,dev-server:7004,dev-server:7005
  elasticsearch:
    rest:
      uris: http://dev-server:9200
  rabbitmq:
    host: dev-server
    username: user
    password: password
  jpa:
    properties:
      hibernate:
        #        show_sql: true
        #        use_sql_comments: true
        #        format_sql: true
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-request-size: 10GB
      max-file-size: 1GB
  #  main:
  #    lazy-initialization: true
  cache:
    redis:
      time-to-live: 600000 #10 minutes
  data:
    mongodb:
      host: dev-server
      database: app
      username: apps
      password: apps
  devtools:
    restart:
      additional-paths:
        - ./application/boot/build/classes/java/main
        - ./application/database/build/classes/java/main
        - ./application/service/build/classes/java/main
        - ./application/utils/build/classes/java/main
        - ./library/extend/build/classes/java/main
        - ./library/lang/build/classes/java/main
server:
  servlet:
    context-path: /api
  port: 3333
