spring:
  datasource:
    url: jdbc:mysql://dev-server:3306/app
    username: apps
    password: apps
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: dev-server
    password: PassW0rds
  elasticsearch:
    rest:
      uris: http://dev-server:9200
  jpa:
    properties:
      hibernate:
        #        show_sql: true
        #        use_sql_comments: true
        #        format_sql: true
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_null
    data:
      mongodb:
        uri: mongodb://dev-server:27017
  servlet:
    multipart:
      max-request-size: 1GB
      max-file-size: 100MB
  main:
    lazy-initialization: true
  cache:
    redis:
      time-to-live: 600000 #10 minutes
server:
  servlet:
    context-path: /api
